name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2

    - name: Install Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: |
        bun install
        cd mdc
        bun install
        cd ..

    - name: Build site
      run: bun run build

    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        cname: qther.de
